export const GET_CITY_BY_COORDS_REQUEST = 'GET_CITY_BY_COORDS_REQUEST'
export const GET_CITY_BY_COORDS_SUCCESS = 'GET_CITY_BY_COORDS_SUCCESS'
export const GET_CITY_BY_COORDS_FAIL = 'GET_CITY_BY_COORDS_FAIL'
