export const FAVORITE_ADD_ITEM = 'FAVORITE_ADD_ITEM'
export const FAVORITE_REMOVE_ITEM = 'FAVORITE_REMOVE_ITEM'

export const FAVORITE_SHOW_ITEM = 'FAVORITE_SHOW_ITEM'
export const FAVORITE_RESET_ITEM = 'FAVORITE_RESET_ITEM'
