export const CURRENT_WEATHER_REQUEST = 'CURRENT_WEATHER_REQUEST'
export const CURRENT_WEATHER_SUCCESS = 'CURRENT_WEATHER_SUCCESS'
export const CURRENT_WEATHER_FAIL = 'CURRENT_WEATHER_FAIL'
export const CURRENT_WEATHER_RESET = 'CURRENT_WEATHER_RESET'

export const FIVE_DAYS_WEATHER_REQUEST = 'FIVE_DAYS_WEATHER_REQUEST'
export const FIVE_DAYS_WEATHER_SUCCESS = 'FIVE_DAYS_WEATHER_SUCCESS'
export const FIVE_DAYS_WEATHER_FAIL = 'FIVE_DAYS_WEATHER_FAIL'
export const FIVE_DAYS_WEATHER_RESET = 'FIVE_DAYS_WEATHER_RESET'
